version: '3.8'

services:
  web:
    build: .
    command: bash -c "bin/rails db:create && bin/rails db:migrate && bundle exec rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql2://username:password@mysql:3306/database
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - mysql
      - redis
      - elasticsearch

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      - DATABASE_URL=mysql2://username:password@mysql:3306/database
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
